import React, {useMemo, useState} from 'react';
import {Player} from '@remotion/player';
import {Upload, Sparkles, Film, WandSparkles, Download, CirclePlay} from 'lucide-react';
import {TechVideo} from './Video';
import {demoScenes, parseSrt, type Scene} from './scenes';

const sample = `1\n00:00:00,000 --> 00:00:03,000\n我从选题开始\n\n2\n00:00:03,000 --> 00:00:06,000\n拆解内容并组织脚本\n\n3\n00:00:06,000 --> 00:00:09,000\n用AI完成配音和数字人\n\n4\n00:00:09,000 --> 00:00:12,000\n最后用动画批量生成视频`;
export default function Studio(){
 const [raw,setRaw]=useState(sample); const [scenes,setScenes]=useState<Scene[]>(demoScenes); const [transparent,setTransparent]=useState(false); const [selected,setSelected]=useState(0); const [uploaded,setUploaded]=useState('示例字幕');
 const duration=Math.max(1,scenes[scenes.length-1]?.end ?? 12);
 const active=useMemo(()=>scenes[selected]??scenes[0],[scenes,selected]);
 const readFile=(f?:File)=>{if(!f)return; const r=new FileReader();r.onload=()=>{setRaw(String(r.result??''));setUploaded(f.name)};r.readAsText(f,'UTF-8')};
 const generate=()=>{const parsed=parseSrt(raw); if(parsed.length){setScenes(parsed);setSelected(0)}else alert('没有识别到有效的 SRT 时间码，请检查文件格式。')};
 const update=(key:'text'|'keyword'|'type',value:string)=>setScenes(old=>old.map((s,i)=>i===selected?{...s,[key]:value}:s));
 const downloadJson=()=>{const blob=new Blob([JSON.stringify({scenes,transparent,format:'1080x1920',fps:30},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='分镜配置.json';a.click();URL.revokeObjectURL(a.href)};
 return <div className="app"><header><div className="brand"><div className="brandIcon"><WandSparkles size={20}/></div><div><b>科技动画工作台</b><small>SRT → AI STORYBOARD → REMOTION</small></div></div><div className="status"><span/> 本地预览模式</div></header>
 <main><section className="intro"><div className="eyebrow"><Sparkles size={14}/> NO-CODE MOTION WORKFLOW</div><h1>让字幕，自动变成<br/><em>科技感动画分镜</em></h1><p>上传 SRT，自动拆分镜头、匹配视觉模板，再预览每一段动画。</p></section>
 <div className="workspace"><section className="panel inputPanel"><div className="panelTitle"><span className="step">01</span><div><h2>导入字幕</h2><p>支持标准 .srt 字幕或直接粘贴文本</p></div></div><label className="dropzone"><Upload size={23}/><b>{uploaded}</b><span>点击选择 SRT 文件</span><input type="file" accept=".srt,.txt,text/plain" onChange={e=>readFile(e.target.files?.[0])}/></label><textarea value={raw} onChange={e=>setRaw(e.target.value)} spellCheck={false} aria-label="字幕内容"/><button className="primary" onClick={generate}><Sparkles size={17}/> 自动生成分镜</button><div className="tip">提示：SRT 时间码会决定每段动画的起止时间。</div></section>
 <section className="panel previewPanel"><div className="panelTitle"><span className="step">02</span><div><h2>动画预览</h2><p>竖屏 9:16 · 1080 × 1920 · 30 FPS</p></div><span className="live"><CirclePlay size={14}/> LIVE</span></div><div className="playerWrap"><div className="player"><Player component={TechVideo} inputProps={{scenes,transparent}} durationInFrames={Math.ceil(duration*30)} fps={30} compositionWidth={1080} compositionHeight={1920} style={{width:'100%',height:'100%'}} controls autoPlay loop/></div></div><div className="previewFoot"><span><Film size={15}/> {scenes.length} 个动画片段</span><span>{duration.toFixed(1)} 秒总时长</span></div></section>
 <section className="panel editPanel"><div className="panelTitle"><span className="step">03</span><div><h2>分镜调整</h2><p>选择任意片段，修改显示内容</p></div></div><div className="sceneList">{scenes.map((s,i)=><button key={s.id} className={`sceneRow ${i===selected?'chosen':''}`} onClick={()=>setSelected(i)}><span className="sceneNum">{String(i+1).padStart(2,'0')}</span><span className="sceneInfo"><b>{s.keyword}</b><small>{s.start.toFixed(1)}s — {s.end.toFixed(1)}s</small></span><span className="sceneArrow">↗</span></button>)}</div>{active&&<div className="editor"><label>动画关键词<input value={active.keyword} onChange={e=>update('keyword',e.target.value)}/></label><label>字幕 / 说明<textarea rows={3} value={active.text} onChange={e=>update('text',e.target.value)}/></label><label>动画模板<select value={active.type} onChange={e=>update('type',e.target.value)}><option value="workflow">流程节点</option><option value="chip">芯片结构</option><option value="data">数据流</option><option value="network">科技网络</option></select></label><label className="check"><input type="checkbox" checked={transparent} onChange={e=>setTransparent(e.target.checked)}/> 预览透明背景</label></div>}<button className="secondary" onClick={downloadJson}><Download size={16}/> 导出分镜配置</button><p className="note">当前网页提供实时预览与分镜配置导出。MP4 渲染需在安装 Node.js 的电脑上运行项目中的 Remotion 命令。</p></section></div>
 <footer>第一版原型 · 文件默认在本地浏览器中处理，不会自动上传字幕。</footer></main></div>
}
